[package]
name = "flash"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
arboard = { version = "3.6", default-features = false, features = ["wayland-data-control"] }
bytemuck = { version = "1", features = ["derive"] }
fontdue = "0.9"
pollster = "0.3"
portable-pty = "0.9.0"
serde = { version = "1", features = ["derive"] }
toml = "1.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
vte = "0.15.0"
wgpu = "0.20"
winit = { version = "0.30", default-features = false, features = ["rwh_06", "wayland", "wayland-dlopen"] }
